#pragma once

struct PathTraceCleanRtxdiDiGuiSnapshot
{
    bool valid = false;
    bool enabled = false;
    bool routeReady = false;
    bool temporal = false;
    bool spatial = false;
    bool bestLights = false;
    bool denoiser = false;
    bool fallback = false;
    bool externalPdfNeeCurrent = false;
    bool externalPdfNeeMode9 = false;
    bool regirEnabled = false;
    bool subview = false;
    bool mirror = false;
    bool superView = false;
    bool sceneBuilt = false;
    bool cleanShader = false;
    bool bindingSet = false;
    bool textureTable = false;
    bool outputTexture = false;
    bool currentReservoir = false;
    bool temporalReservoir = false;
    bool previousReservoir = false;
    bool previousReservoirValid = false;
    bool portalProofDomain = false;
    bool fullAnalyticDomain = false;
    bool doomRadiusCutoff = false;
    bool relaxBrdfGates = false;
    bool doomTargetFloor = false;
    bool bypassLightUniverse = false;
    bool requireProvenDoomLights = false;
    int view = 0;
    int lightMode = 0;
    int area = -1;
    int drawSurfs = 0;
    int width = 0;
    int height = 0;
    int regirMode = 0;
    int regirCenterMode = 0;
    int regirLightsPerCell = 0;
    int regirBuildSamples = 0;
    int frameIndex = 0;
    int analyticDomainFreezeMs = 0;
    int doomColorSource = 0;
    int temporalBiasCorrection = 0;
    int temporalMaxHistory = 0;
    int candidateOverride = 0;
    int view10LightCount = 1;
    int view10LightStart = 0;
    bool view10PortalDomain = false;
    unsigned int cleanCandidates = 0;
    unsigned int cleanCurrentAnalytic = 0;
    unsigned int cleanPortalAnalytic = 0;
    unsigned int cleanCurrentAnalyticIdentity = 0;
    unsigned int cleanPreviousAnalytic = 0;
    unsigned int cleanPreviousAnalyticIdentity = 0;
    unsigned int cleanAnalyticRemap = 0;
    unsigned int cleanReservoirCount = 0;
    unsigned int cleanHistoryResetCount = 0;
    unsigned long long cleanHistorySignature = 0;
    unsigned int temporalFlags = 0;
    float regirCellSize = 0.0f;
    unsigned int regirGridX = 0;
    unsigned int regirGridY = 0;
    unsigned int regirGridZ = 0;
    unsigned int regirCandidateSlots = 0;
    const char* route = "unknown";
    const char* behavior = "unknown";
    const char* regirFirstMissing = "unknown";
};

void PathTraceCleanRtxdiDiPublishGuiSnapshot(const PathTraceCleanRtxdiDiGuiSnapshot& snapshot);
bool PathTraceCleanRtxdiDiGetGuiSnapshot(PathTraceCleanRtxdiDiGuiSnapshot& snapshot);
