#ifndef RB_PATH_TRACING_RTXDI_PT_INITIAL_SAMPLING_SHADOW_HLSLI
#define RB_PATH_TRACING_RTXDI_PT_INITIAL_SAMPLING_SHADOW_HLSLI

#ifndef RTXDI_RESTIR_PT_INITIAL_SAMPLING
#define RTXDI_RESTIR_PT_INITIAL_SAMPLING
#endif

#include "../../cleanroom_common/restir_pt_initial_sampling.hlsli"

#endif
