#ifndef RB_PATH_TRACING_RTXDI_PT_PATH_TRACER_RANDOM_CONTEXT_SHADOW_HLSLI
#define RB_PATH_TRACING_RTXDI_PT_PATH_TRACER_RANDOM_CONTEXT_SHADOW_HLSLI

#include "../../cleanroom_common/restir_pt_path_tracer_random_context.hlsli"

#endif
