#ifndef RB_PATH_TRACING_RAB_UNIFIED_LIGHT_RECORD_HLSLI
#define RB_PATH_TRACING_RAB_UNIFIED_LIGHT_RECORD_HLSLI

static const uint PATH_TRACE_UNIFIED_LIGHT_TYPE_INVALID = 0u;
static const uint PATH_TRACE_UNIFIED_LIGHT_TYPE_EMISSIVE_TRIANGLE = 1u;
static const uint PATH_TRACE_UNIFIED_LIGHT_TYPE_DOOM_ANALYTIC = 2u;
static const uint PATH_TRACE_UNIFIED_LIGHT_INVALID_INDEX = 0xffffffffu;

static const uint PATH_TRACE_RLU_LIGHT_FLAG_CURRENT_SAMPLEABLE = 1u << 24u;
static const uint PATH_TRACE_RLU_LIGHT_FLAG_STABLE_CACHEABLE = 1u << 25u;
static const uint PATH_TRACE_RLU_LIGHT_FLAG_UNSTABLE_DYNAMIC = 1u << 26u;
static const uint PATH_TRACE_RLU_LIGHT_CLASSIFICATION_FLAG_MASK =
    PATH_TRACE_RLU_LIGHT_FLAG_CURRENT_SAMPLEABLE |
    PATH_TRACE_RLU_LIGHT_FLAG_STABLE_CACHEABLE |
    PATH_TRACE_RLU_LIGHT_FLAG_UNSTABLE_DYNAMIC;

static const uint PATH_TRACE_RLU_STABILITY_REASON_NO_REMAP = 1u << 16u;
static const uint PATH_TRACE_RLU_STABILITY_REASON_PAYLOAD_CHANGED = 1u << 17u;
static const uint PATH_TRACE_RLU_STABILITY_REASON_UNPROVEN_CONTINUITY = 1u << 18u;
static const uint PATH_TRACE_RLU_STABILITY_REASON_UNKNOWN_IDENTITY = 1u << 19u;
static const uint PATH_TRACE_RLU_STABILITY_REASON_DUPLICATE_IDENTITY = 1u << 20u;
static const uint PATH_TRACE_RLU_STABILITY_REASON_PORTAL_DISCONNECTED = 1u << 21u;
static const uint PATH_TRACE_RLU_STABILITY_REASON_OUT_OF_SELECTED_AREA = 1u << 22u;
static const uint PATH_TRACE_RLU_STABILITY_REASON_FLAG_MASK =
    PATH_TRACE_RLU_STABILITY_REASON_NO_REMAP |
    PATH_TRACE_RLU_STABILITY_REASON_PAYLOAD_CHANGED |
    PATH_TRACE_RLU_STABILITY_REASON_UNPROVEN_CONTINUITY |
    PATH_TRACE_RLU_STABILITY_REASON_UNKNOWN_IDENTITY |
    PATH_TRACE_RLU_STABILITY_REASON_DUPLICATE_IDENTITY |
    PATH_TRACE_RLU_STABILITY_REASON_PORTAL_DISCONNECTED |
    PATH_TRACE_RLU_STABILITY_REASON_OUT_OF_SELECTED_AREA;
static const uint PATH_TRACE_RLU_STABILITY_FLAG_MASK =
    PATH_TRACE_RLU_LIGHT_CLASSIFICATION_FLAG_MASK |
    PATH_TRACE_RLU_STABILITY_REASON_FLAG_MASK;

struct PathTraceUnifiedLightRecord
{
    float4 positionAndRadius;
    float4 normalAndArea;
    float4 radianceAndLuminance;
    float4 uvOrDoomParams;

    uint type;
    uint sourceIndex;
    uint flags;
    uint materialOrLightId;

    uint instanceId;
    uint primitiveIndex;
    uint identityA;
    uint identityB;

    float sourcePdf;
    float sourceWeight;
    uint previousIndex;
    uint padding0;
};

#endif
