#define RB_PT_ENABLE_RESTIR 1
#define RB_PT_ENABLE_RESTIR_TEMPORAL 1
#define RB_PT_ENABLE_RESTIR_SPATIAL 1
#define RB_PT_ENABLE_RESTIR_SPATIAL_SHADING 1
#define RB_PT_RESTIR_SPATIAL_CONSUMES_TEMPORAL_PREPASS 1
#define RB_PT_RESTIR_SPATIAL_CONSUMES_SPATIAL_PREPASS 1
#define RB_PT_ENABLE_RESTIR_MODE18_DIRECT 1
#define RB_PT_FORCE_DEBUG_MODE 18u
#include "pathtrace_smoke.rt.hlsl"
